.TH "include/mml Directory Reference" 3 "Tue Jun 4 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdefinitions\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfile\&.hpp\fP"
.br
.RI "This file includes functions regarding the files\&. It might only work on linux as some commands might be os-dependent\&. The main function of here is to copy files\&. It also has other functions such as checking if a file exists\&. "
.ti -1c
.RI "file \fBhelp\&.hpp\fP"
.br
.RI "Contains functions to print help pages\&. "
.ti -1c
.RI "file \fBlog\&.hpp\fP"
.br
.RI "Contains different functions for logging\&. "
.ti -1c
.RI "file \fBshell\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstandards\&.hpp\fP"
.br
.ti -1c
.RI "file \fBthread\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTimer\&.hpp\fP"
.br
.RI "Contains different functions and a class concerning timing\&. "
.ti -1c
.RI "file \fBUnix\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvector\&.hpp\fP"
.br
.RI "Class vector\&. "
.in -1c
