.TH "src/arg.cpp" 3 "Thu May 23 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/arg.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'mml/functions\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br
\fC#include <limits>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
