.TH "include/mml/definitions.hpp" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/definitions.hpp \- Some definitions used in the library\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_1B\fP   8"
.br
.ti -1c
.RI "#define \fB_1K\fP   1000"
.br
.ti -1c
.RI "#define \fB_1KB\fP   1024"
.br
.ti -1c
.RI "#define \fB_1M\fP   1000000"
.br
.ti -1c
.RI "#define \fB_1MB\fP   1048576"
.br
.ti -1c
.RI "#define \fB_10M\fP   10000000"
.br
.ti -1c
.RI "#define \fB_10MB\fP   10485760"
.br
.ti -1c
.RI "#define \fB_100M\fP   100000000"
.br
.ti -1c
.RI "#define \fB_100MB\fP   104857600"
.br
.ti -1c
.RI "#define \fB_1G\fP   1000000000"
.br
.ti -1c
.RI "#define \fB_1GB\fP   1073741824"
.br
.ti -1c
.RI "#define \fBS_DEVICE\fP   6"
.br
.ti -1c
.RI "#define \fBS_CHARDEV\fP   2"
.br
.ti -1c
.RI "#define \fBS_DIR\fP   4"
.br
.ti -1c
.RI "#define \fBS_FIFO\fP   1"
.br
.ti -1c
.RI "#define \fBS_SYMLNK\fP   10"
.br
.ti -1c
.RI "#define \fBS_FILE\fP   8"
.br
.ti -1c
.RI "#define \fBS_SOCK\fP   12"
.br
.ti -1c
.RI "#define \fBS_OTHER\fP   14"
.br
.ti -1c
.RI "#define \fB_sec\fP   0"
.br
.ti -1c
.RI "#define \fB_min\fP   1"
.br
.ti -1c
.RI "#define \fB_hour\fP   2"
.br
.ti -1c
.RI "#define \fB_day\fP   3"
.br
.ti -1c
.RI "#define \fB_month\fP   4"
.br
.ti -1c
.RI "#define \fB_year\fP   5"
.br
.ti -1c
.RI "#define \fB_st1\fP   6"
.br
.ti -1c
.RI "#define \fB_weekday\fP   7"
.br
.ti -1c
.RI "#define \fB_yearday\fP   8"
.br
.ti -1c
.RI "#define \fB_kw\fP   9"
.br
.ti -1c
.RI "#define \fB_y_sec\fP   60*60*24*365\&.15"
.br
.ti -1c
.RI "#define \fB_d_sec\fP   60*60*24"
.br
.in -1c
.SH "Detailed Description"
.PP 
Some definitions used in the library\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-13
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define _100M   100000000"

.SS "#define _100MB   104857600"

.SS "#define _10M   10000000"

.SS "#define _10MB   10485760"

.SS "#define _1B   8"

.SS "#define _1G   1000000000"

.SS "#define _1GB   1073741824"

.SS "#define _1K   1000"

.SS "#define _1KB   1024"

.SS "#define _1M   1000000"

.SS "#define _1MB   1048576"

.SS "#define _d_sec   60*60*24"

.SS "#define _day   3"

.SS "#define _hour   2"

.SS "#define _kw   9"

.SS "#define _min   1"

.SS "#define _month   4"

.SS "#define _sec   0"

.SS "#define _st1   6"

.SS "#define _weekday   7"

.SS "#define _y_sec   60*60*24*365\&.15"

.SS "#define _year   5"

.SS "#define _yearday   8"

.SS "#define S_CHARDEV   2"

.SS "#define S_DEVICE   6"

.SS "#define S_DIR   4"

.SS "#define S_FIFO   1"

.SS "#define S_FILE   8"

.SS "#define S_OTHER   14"

.SS "#define S_SOCK   12"

.SS "#define S_SYMLNK   10"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
