.TH "include/mml/definitions.hpp" 3 "Tue May 21 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/definitions.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_1B\fP   8"
.br
.ti -1c
.RI "#define \fB_1K\fP   1000"
.br
.ti -1c
.RI "#define \fB_1KB\fP   1024"
.br
.ti -1c
.RI "#define \fB_1M\fP   1000000"
.br
.ti -1c
.RI "#define \fB_1MB\fP   1048576"
.br
.ti -1c
.RI "#define \fB_10M\fP   10000000"
.br
.ti -1c
.RI "#define \fB_10MB\fP   10485760"
.br
.ti -1c
.RI "#define \fB_100M\fP   100000000"
.br
.ti -1c
.RI "#define \fB_100MB\fP   104857600"
.br
.ti -1c
.RI "#define \fB_1G\fP   1000000000"
.br
.ti -1c
.RI "#define \fB_1GB\fP   1073741824"
.br
.ti -1c
.RI "#define \fBS_DEVICE\fP   6"
.br
.ti -1c
.RI "#define \fBS_CHARDEV\fP   2"
.br
.ti -1c
.RI "#define \fBS_DIR\fP   4"
.br
.ti -1c
.RI "#define \fBS_FIFO\fP   1"
.br
.ti -1c
.RI "#define \fBS_SYMLNK\fP   10"
.br
.ti -1c
.RI "#define \fBS_FILE\fP   8"
.br
.ti -1c
.RI "#define \fBS_SOCK\fP   12"
.br
.ti -1c
.RI "#define \fB_sec\fP   0"
.br
.ti -1c
.RI "#define \fB_min\fP   1"
.br
.ti -1c
.RI "#define \fB_hour\fP   2"
.br
.ti -1c
.RI "#define \fB_day\fP   3"
.br
.ti -1c
.RI "#define \fB_month\fP   4"
.br
.ti -1c
.RI "#define \fB_year\fP   5"
.br
.ti -1c
.RI "#define \fB_st1\fP   6"
.br
.ti -1c
.RI "#define \fB_weekday\fP   7"
.br
.ti -1c
.RI "#define \fB_yearday\fP   8"
.br
.ti -1c
.RI "#define \fB_kw\fP   9"
.br
.ti -1c
.RI "#define \fB_y_sec\fP   60*60*24*365"
.br
.ti -1c
.RI "#define \fB_m_sec\fP"
.br
.ti -1c
.RI "#define \fB_d_sec\fP"
.br
.ti -1c
.RI "#define \fB_check_root_log\fP   '/var/log/check_root\&.log'"
.br
.ti -1c
.RI "#define \fB_cifs_log\fP   '/var/log/cifs\&.log'"
.br
.ti -1c
.RI "#define \fB_cop_log\fP   '/var/log/cop\&.log'"
.br
.ti -1c
.RI "#define \fB_copy_log\fP   '/var/log/copy\&.log'"
.br
.ti -1c
.RI "#define \fB_statistik_log\fP   '/var/log/statistik\&.log'"
.br
.ti -1c
.RI "#define \fB_timer_log\fP   '/var/log/timer\&.log'"
.br
.ti -1c
.RI "#define \fB_backup_log\fP   '/var/log/backup\&.log'"
.br
.ti -1c
.RI "#define \fB_alma\fP   '192\&.168\&.20\&.99'"
.br
.ti -1c
.RI "#define \fB_printer\fP   '192\&.168\&.20\&.20'"
.br
.ti -1c
.RI "#define \fB_location\fP   (std::string) 'to nowhere'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _100M   100000000"

.SS "#define _100MB   104857600"

.SS "#define _10M   10000000"

.SS "#define _10MB   10485760"

.SS "#define _1B   8"

.SS "#define _1G   1000000000"

.SS "#define _1GB   1073741824"

.SS "#define _1K   1000"

.SS "#define _1KB   1024"

.SS "#define _1M   1000000"

.SS "#define _1MB   1048576"

.SS "#define _alma   '192\&.168\&.20\&.99'"

.SS "#define _backup_log   '/var/log/backup\&.log'"

.SS "#define _check_root_log   '/var/log/check_root\&.log'"

.SS "#define _cifs_log   '/var/log/cifs\&.log'"

.SS "#define _cop_log   '/var/log/cop\&.log'"

.SS "#define _copy_log   '/var/log/copy\&.log'"

.SS "#define _d_sec"

.SS "#define _day   3"

.SS "#define _hour   2"

.SS "#define _kw   9"

.SS "#define _location   (std::string) 'to nowhere'"

.SS "#define _m_sec"

.SS "#define _min   1"

.SS "#define _month   4"

.SS "#define _printer   '192\&.168\&.20\&.20'"

.SS "#define _sec   0"

.SS "#define _st1   6"

.SS "#define _statistik_log   '/var/log/statistik\&.log'"

.SS "#define _timer_log   '/var/log/timer\&.log'"

.SS "#define _weekday   7"

.SS "#define _y_sec   60*60*24*365"

.SS "#define _year   5"

.SS "#define _yearday   8"

.SS "#define S_CHARDEV   2"

.SS "#define S_DEVICE   6"

.SS "#define S_DIR   4"

.SS "#define S_FIFO   1"

.SS "#define S_FILE   8"

.SS "#define S_SOCK   12"

.SS "#define S_SYMLNK   10"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
