.TH "include/mml/file.hpp" 3 "Sat Jun 8 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/file.hpp \- This file includes functions regarding the files\&. It might only work on linux as some commands might be os-dependent\&. The main function of here is to copy files\&. It also has other functions such as checking if a file exists\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'mml/standards\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmml\fP"
.br
.ti -1c
.RI " \fBmml::file\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmml::file::add_twofiles\fP (std::string filepath_input1, std::string filepath_input2, std::string filepath_output)"
.br
.RI "Opens two textfiles and writes it in another\&. "
.ti -1c
.RI "bool \fBmml::file::byteCopy\fP (const std::string &src, const std::string &dest, std::size_t blockSize, bool progress=false)"
.br
.RI "Copy a file\&. "
.ti -1c
.RI "int \fBmml::file::copy\fP (\fBmml::string\fP src, \fBmml::string\fP dst, std::string name_in='', std::string name_ex='', size_t blocksize=\fB_100MB\fP, bool verbose=false, bool verbose_debug=false, bool all=false, bool recursive=false, bool force=false, bool progress=false, bool falsewrite=false)"
.br
.RI "Copy the content of the path to a new one\&. "
.ti -1c
.RI "bool \fBmml::file::equal\fP (std::string src, std::string dst)"
.br
.RI "Compare two files by using the SHA256 algorithm\&. Only works for linux\&. "
.ti -1c
.RI "int32_t \fBmml::file::filetype\fP (std::string filepath)"
.br
.RI "Determine the type of an object (directory, file, etc\&.) "
.ti -1c
.RI "std::string \fBmml::file::humanread\fP (std::size_t number)"
.br
.RI "Convert number into human readable number\&. "
.ti -1c
.RI "std::size_t \fBmml::file::num_lines\fP (std::string path)"
.br
.RI "Determine number of lines in a file\&. "
.ti -1c
.RI "int \fBmml::file::Program_exist\fP (std::string program)"
.br
.RI "Checks if a program exists\&. "
.ti -1c
.RI "void \fBmml::file::remove\fP (std::string file)"
.br
.ti -1c
.RI "void \fBmml::file::set_date_dir\fP (\fBmml::string\fP src, \fBmml::string\fP dst, std::vector< std::string > ends={'NEF','tif','JPG','jpg','MP4','MOV','PNG','HEIC','JPEG','jpeg','pdf', 'PDF'}, bool recursive=false, bool all=false, bool verbose=false)"
.br
.ti -1c
.RI "std::size_t \fBmml::file::size\fP (const std::string &filename)"
.br
.RI "Calculates the size of a file\&. "
.ti -1c
.RI "std::string \fBmml::file::size_human\fP (const std::string &filename, bool verbose=true)"
.br
.RI "Calculates the size of a file\&. "
.ti -1c
.RI "std::string \fBmml::file::size_dir\fP (\fBmml::string\fP &dir, std::string include='', std::string exclude='', bool verbose=false, bool recursive=false, bool all=false, bool human_readable=false) noexcept"
.br
.RI "Calculates the size of a directory structure\&. "
.ti -1c
.RI "time_t \fBmml::file::time_mod\fP (const std::string &filename)"
.br
.RI "Returns the last modified time of a file in seconds\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file includes functions regarding the files\&. It might only work on linux as some commands might be os-dependent\&. The main function of here is to copy files\&. It also has other functions such as checking if a file exists\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
