.TH "src/file.cpp" 3 "Tue Jun 4 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/file.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <bits/local_lim\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include 'mml\&.hpp'\fP
.br
\fC#include 'mml/file\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmml::thread::Thread\fP \fBmml_thread\fP"
.br
.ti -1c
.RI "\fBmml::string\fP \fBmml_actual_file\fP = ''"
.br
.ti -1c
.RI "bool \fBmml_progressing\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Funktionen für Dateien 
.SH "Variable Documentation"
.PP 
.SS "\fBmml::string\fP mml_actual_file = ''"

.SS "bool mml_progressing = false"

.SS "\fBmml::thread::Thread\fP mml_thread"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
