.TH "src/functions.cpp" 3 "Thu May 23 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/functions.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <sys/mount\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include 'mml/functions\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br
\fC#include 'mml/Unix\&.hpp'\fP
.br
\fC#include 'mml/Thread\&.hpp'\fP
.br
\fC#include 'mml/definitions\&.hpp'\fP
.br

.SS "Variables"

.PP
.RI "\fBfunctions\&.cpp\fP"
.br

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Funktionen 
.PP
.in +1c
.in +1c
.ti -1c
.RI "\fBmml::string\fP \fBmml_pass\fP"
.br
.ti -1c
.RI "\fBmml::string\fP \fBmml_mount_name\fP"
.br
.in -1c
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmml::string\fP mml_mount_name"

.SS "\fBmml::string\fP mml_pass"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
