.TH "include/mml/functions.hpp" 3 "Sat Jun 1 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/functions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <random>\fP
.br
\fC#include <float\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmml\fP"
.br
.ti -1c
.RI " \fBmml::shell\fP"
.br
.ti -1c
.RI " \fBmml::functions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr uint32_t \fBmml::functions::const_string_hash\fP (const char *string)"
.br
.RI "Forms a hash value of a string\&. "
.ti -1c
.RI "template<typename templ > void \fBmml::functions::erase\fP (std::vector< templ > &data)"
.br
.RI "Empty a vector\&. "
.in -1c
.PP
.RI "\fBfunctions\&.cpp\fP"
.br

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Funktionen 
.PP
.in +1c
.in +1c
.ti -1c
.RI "std::string \fBmml::functions::declare_month\fP (int month_nr)"
.br
.RI "Convert month number to month string\&. "
.ti -1c
.RI "template<typename templ > templ \fBmml::functions::get_random\fP (templ min=0, templ max=100)"
.br
.RI "Create a random number in a defined range\&. "
.ti -1c
.RI "template<typename templ > templ \fBmml::functions::smallest_num\fP (std::vector< templ > values, std::size_t pos=0)"
.br
.RI "Return the smallest number\&. "
.ti -1c
.RI "std::string \fBmml::functions::random_str\fP (size_t letters=10, std::string start='')"
.br
.RI "Create a random, lower-case string\&. "
.ti -1c
.RI "std::size_t \fBmml::functions::digits\fP (double number)"
.br
.RI "Determine number of digits of a double number\&. "
.ti -1c
.RI "std::vector< double > \fBmml::functions::Get_Values\fP (std::string filepath, double min_value)"
.br
.RI "Write numbers after an equal sign from a file into a vector (format: [sth]=1\&.0) "
.ti -1c
.RI "std::string \fBmml::functions::lower\fP (std::string input)"
.br
.RI "Alle Werte im String als Kleinbuchstaben\&. "
.in -1c
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
\fBNote\fP
.RS 4
Enthält verschiedene Funktionen 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
