.TH "include/mml/help.hpp" 3 "Wed May 22 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/help.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmml\fP"
.br
.ti -1c
.RI " \fBmml::help\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmml::help::check_root\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::cifs\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::convert\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::cop\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::copy\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::farben\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::finanzen\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::hhelp\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::hhelp_commands\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::R_cop\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::R_dns_filter\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::rechner\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::sizeof_h\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::statistik\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::timer\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::todos\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::userinfo\fP ()"
.br
.ti -1c
.RI "void \fBmml::help::foot\fP (std::string version, std::string month, int year)"
.br
.ti -1c
.RI "void \fBmml::help::header\fP (std::string befehl, std::string option='')"
.br
.ti -1c
.RI "void \fBmml::help::help\fP (\fBmml::string\fP output)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
\fBNote\fP
.RS 4
Enthält verschiedene Hilfeseiten für C++-Programme 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
