.TH "src/help.cpp" 3 "Tue May 21 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/help.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'mml/help\&.hpp'\fP
.br
\fC#include <mml\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 
: 
.PP
\fBAuthor\fP
.RS 4
Mike Moser : : : 
.RE
.PP
\fBNote\fP
.RS 4
This file contains functions to print out a help page for the different 'programes' here : 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
