.TH "src/help.cpp" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/help.cpp \- This file contains functions to print out a help page for the different 'programes' here\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'mml/help\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
This file contains functions to print out a help page for the different 'programes' here\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-13
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
