.TH "include/mml/help.hpp" 3 "Mon Jun 10 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/help.hpp \- Contains functions to print help pages\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmml\fP"
.br
.ti -1c
.RI " \fBmml::help\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmml::help::foot\fP (std::string version, std::string month, int year, std::string author) noexcept"
.br
.RI "Print the foot line with notes to author and date\&. "
.ti -1c
.RI "void \fBmml::help::header\fP (std::string command, std::string option='') noexcept"
.br
.RI "Print out a header\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains functions to print help pages\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
