.TH "src/log.cpp" 3 "Mon Jun 10 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/log.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mml/log\&.hpp'\fP
.br
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include 'mml/file\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
