.TH "include/mml/log.hpp" 3 "Tue May 21 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/log.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'standards\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmml::log\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmml\fP"
.br
.ti -1c
.RI " \fBmml::Unix\fP"
.br
.ti -1c
.RI " \fBmml::file\fP"
.br
.ti -1c
.RI " \fBmml::shell\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmml::file::remove\fP (std::string file)"
.br
.ti -1c
.RI "void \fBmml::shell::error\fP (std::string text)"
.br
.in -1c
.PP
.RI "\fBfunctions\&.cpp\fP"
.br

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Funktionen 
.PP
.in +1c
.in +1c
.ti -1c
.RI "bool \fBmml::Unix::exist\fP (std::string path)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
\fBNote\fP
.RS 4
Enthält verschiedene Funktionen fürs logging 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
