.TH "mml" 3 "Wed May 22 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBfile\fP"
.br
.ti -1c
.RI " \fBfunctions\fP"
.br
.ti -1c
.RI " \fBhelp\fP"
.br
.ti -1c
.RI " \fBshell\fP"
.br
.ti -1c
.RI " \fBthread\fP"
.br
.ti -1c
.RI " \fBUnix\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog\fP"
.br
.ti -1c
.RI "class \fBstring\fP"
.br
.ti -1c
.RI "class \fBTimer\fP"
.br
.ti -1c
.RI "class \fBvector\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename templ > double \fBatob\fP (const templ &t)"
.br
.ti -1c
.RI "template<typename T > double \fBatof\fP (const T &t)"
.br
.ti -1c
.RI "template<typename T > int \fBatoi\fP (const T &t)"
.br
.ti -1c
.RI "template<typename templ > void \fBcout\fP (std::vector< templ > const &vec)"
.br
.ti -1c
.RI "template<typename T > \fBmml::string\fP \fBto_string\fP (const T &t)"
.br
.in -1c
.PP
.RI "\fBstandards\&.cpp\fP"
.br

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Standardfunktionen 
.PP
.in +1c
.in +1c
.ti -1c
.RI "bool \fBcheck_root\fP (std::string programme='')"
.br
.ti -1c
.RI "uint32_t \fBdate\fP (int info, time_t time1=\-1)"
.br
.ti -1c
.RI "std::string \fBdate\fP (\fBmml::string\fP value, std::string separator1=':', std::string separator2='\&.')"
.br
.ti -1c
.RI "bool \fBrange\fP (std::size_t number)"
.br
.ti -1c
.RI "bool \fBrange\fP (std::size_t, std::size_t)"
.br
.ti -1c
.RI "double \fBround\fP (double number, uint16_t digits)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Bibliothek shell\&.h Enthält verschiedene Funktionen mit namespace shell 
.SH "Function Documentation"
.PP 
.SS "template<typename templ > double mml::atob (const templ & t)"
Converts value to bool
.PP
\fBParameters\fP
.RS 4
\fItempl\fP Value 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "template<typename T > double mml::atof (const T & t)"
Converts value to bool
.PP
\fBParameters\fP
.RS 4
\fItempl\fP Value 
.RE
.PP
\fBReturns\fP
.RS 4
double 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "template<typename T > int mml::atoi (const T & t)"
Converts value to int
.PP
\fBParameters\fP
.RS 4
\fItempl\fP Value 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "bool mml::check_root (std::string programme = \fC''\fP)"
Check if program executed as root 
.PP
\fBParameters\fP
.RS 4
\fIstd::string,optional\fP Programme name 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.SS "template<typename templ > void mml::cout (std::vector< templ > const & vec)"
Prints the values of a vector
.PP
\fBParameters\fP
.RS 4
\fIstd::vector<templ>\fP Vector to be printed 
.RE
.PP

.SS "uint32_t mml::date (int info, time_t time1 = \fC\-1\fP)"
Returns the wished info from the time (like date etc\&.) Options are:
.IP "\(bu" 2
0: Seconds
.IP "\(bu" 2
1: Minutes
.IP "\(bu" 2
2: Hours
.IP "\(bu" 2
3: Day
.IP "\(bu" 2
4: Month
.IP "\(bu" 2
5: Year
.IP "\(bu" 2
6: Summertime
.IP "\(bu" 2
7: Weekday (Days since sunday)
.IP "\(bu" 2
8: Yearday (Days since New Year)
.IP "\(bu" 2
9: kw
.PP
.PP
\fBParameters\fP
.RS 4
\fIint\fP Determines what information is printed 
.br
\fItime_t\fP Time for which the information is printed\&. -1 => Actual time now\&. 
.RE
.PP
\fBReturns\fP
.RS 4
unsigned integer 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::string mml::date (\fBmml::string\fP value, std::string separator1 = \fC':'\fP, std::string separator2 = \fC'\&.'\fP)"
Returns the actual date and/or time as a std::string 
.PP
\fBParameters\fP
.RS 4
\fI\fBmml::string\fP\fP Determines what information is printed\&.
.IP "\(bu" 2
'Date' : DD\&.MM\&.YYYY (based on separator1)
.IP "\(bu" 2
'Time' : HH:MM:SS (based on separator1)
.IP "\(bu" 2
'Date+Time' : Complete date in format DD\&.MM\&.YYYY HH:MM:SS\&.
.IP "\(bu" 2
'Date1+Time' : Compete date in format YYYY\&.MM\&.DD HH:MM:SS\&. 
.PP
.br
\fIstd::string,optional\fP First separation sign for the date 
.br
\fIstd::string,optional\fP Second separation sign for the time
.RE
.PP
\fBReturns\fP
.RS 4
std::string 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "bool mml::range (std::size_t number)"

.PP
\fBNote\fP
.RS 4
Überprüfen, ob maximalert Wert von std::size_t erreicht
.RE
.PP
\fBParameters\fP
.RS 4
\fInumber\fP Number to be checked
.RE
.PP
\fBReturns\fP
.RS 4
true (kleiner als max Wert) oder false 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "bool mml::range (std::size_t number1, std::size_t number2)"

.PP
\fBNote\fP
.RS 4
Überprüfen, ob maximalert Wert von std::size_t erreicht
.RE
.PP
\fBParameters\fP
.RS 4
\fInumber1\fP Number to be checked 
.br
\fInumber2\fP Number to be checked
.RE
.PP
\fBReturns\fP
.RS 4
true (kleiner als max Wert) oder false 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "double mml::round (double number, uint16_t digits)"

.PP
\fBNote\fP
.RS 4
Zahl runden
.RE
.PP
\fBParameters\fP
.RS 4
\fInumber\fP Number which is rounded 
.br
\fIdigits\fP To which digit it is rounded
.RE
.PP
\fBReturns\fP
.RS 4
gerundete double Zahl 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "template<typename T > \fBmml::string\fP mml::to_string (const T & t)"

.PP
\fBNote\fP
.RS 4
Wert in \fBmml::string\fP umwandeln
.RE
.PP
\fBParameters\fP
.RS 4
\fIt\fP Value to be changed 
.RE
.PP
\fBReturns\fP
.RS 4
\fBmml::string\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
