.TH "mml::shell" 3 "Sun Jul 14 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::shell
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBarg\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBerror\fP (std::string text)"
.br
.RI "Print an error in red colour and exit the program\&. "
.ti -1c
.RI "void \fBbackground\fP (\fBstring\fP colour)"
.br
.RI "Change background of the shell\&. "
.ti -1c
.RI "void \fBchapter\fP (std::string text, bool newline=true)"
.br
.RI "Print a chapter of a help page\&. "
.ti -1c
.RI "void \fBcout\fP (\fBmml::string\fP text, bool newline=true, std::string colour='lightgreen')"
.br
.RI "Print to the shell\&. "
.ti -1c
.RI "void \fBformation\fP (\fBstring\fP format)"
.br
.RI "Change the formation of printed texts in the shell\&. "
.ti -1c
.RI "void \fBletter\fP (\fBstring\fP colour)"
.br
.RI "Change printed text colour\&. "
.ti -1c
.RI "void \fBnormal\fP ()"
.br
.RI "Reverse changes in the print behaviour of the shell\&. "
.ti -1c
.RI "void \fBnote\fP (std::string text, bool newline=true)"
.br
.RI "Print a note in lightgray\&. "
.ti -1c
.RI "void \fBoption\fP (std::string option, std::string descr)"
.br
.RI "Print an option in a help page\&. "
.ti -1c
.RI "std::string \fBpassword\fP (std::string print, std::string add)"
.br
.RI "Input of a password\&. "
.ti -1c
.RI "void \fBwarn\fP (std::string text, bool newline=true)"
.br
.RI "Print a warning and exit the program\&. "
.ti -1c
.RI "void \fBwarn_opt\fP (std::string text, bool newline=true)"
.br
.RI "Print a warning without exiting the program\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mml::shell::background (\fBmml::string\fP colour)"

.PP
Change background of the shell\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolour\fP background colour 
.RE
.PP

.SS "void mml::shell::chapter (std::string text, bool newline = \fCtrue\fP)"

.PP
Print a chapter of a help page\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP chapter title 
.br
\fInewline\fP Print a new line 
.RE
.PP

.SS "void mml::shell::cout (\fBmml::string\fP text, bool newline = \fCtrue\fP, std::string colour = \fC'lightgreen'\fP)"

.PP
Print to the shell\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP The text to be printed 
.br
\fInewline\fP New line at the end 
.br
\fIcolour\fP which colour is used for highligting 
.RE
.PP
\fBNote\fP
.RS 4
Text within [] is highlighted 
.RE
.PP

.SS "void mml::shell::error (std::string text)"

.PP
Print an error in red colour and exit the program\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP to be printed 
.RE
.PP
\fBNote\fP
.RS 4
This function exits the program 
.RE
.PP

.SS "void mml::shell::formation (\fBmml::string\fP format1)"

.PP
Change the formation of printed texts in the shell\&. 
.PP
\fBParameters\fP
.RS 4
\fIformat\fP Format
.RE
.PP
Possible options are 'normal', 'fat', 'cursive', 'underline', 'blink', 'reverse'
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "void mml::shell::letter (\fBmml::string\fP colour)"

.PP
Change printed text colour\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolour\fP paint of the letters
.RE
.PP
Options are black, darkgray, (light)red, (light)green, brown, yellow, (light)blue, (light)purple, (light)cyan, white, lightgray, normal
.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Programm \fBshell\&.cpp\fP Enthält verschiedene Funktionen 
.SS "void mml::shell::normal ()"

.PP
Reverse changes in the print behaviour of the shell\&. 
.SS "void mml::shell::note (std::string text, bool newline = \fCtrue\fP)"

.PP
Print a note in lightgray\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP to be printed 
.br
\fInewline\fP print newline 
.RE
.PP

.SS "void mml::shell::option (std::string option, std::string descr)"

.PP
Print an option in a help page\&. 
.PP
\fBParameters\fP
.RS 4
\fIoption\fP Name of the option used 
.br
\fIdescr\fP Description of the option 
.RE
.PP

.SS "std::string mml::shell::password (std::string print, std::string add)"

.PP
Input of a password\&. 
.PP
\fBParameters\fP
.RS 4
\fIprint\fP text to be printed when the code asks for the password 
.br
\fIadd\fP additional text printed after \fCprint\fP 
.RE
.PP
\fBReturns\fP
.RS 4
input 
.RE
.PP

.SS "void mml::shell::warn (std::string text, bool newline = \fCtrue\fP)"

.PP
Print a warning and exit the program\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP Text to be printed 
.br
\fInewline\fP Print new line 
.RE
.PP

.SS "void mml::shell::warn_opt (std::string text, bool newline = \fCtrue\fP)"

.PP
Print a warning without exiting the program\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP Text to be printed 
.br
\fInewline\fP Print a new line 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
