.TH "mml::help" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::help
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfoot\fP (std::string version, std::string month, int year, std::string author) noexcept"
.br
.RI "Print the foot line with notes to author and date\&. "
.ti -1c
.RI "void \fBheader\fP (std::string command, std::string option='') noexcept"
.br
.RI "Print out a header\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mml::help::foot (std::string version, std::string month, int year, std::string author)\fC [noexcept]\fP"

.PP
Print the foot line with notes to author and date\&. 
.PP
\fBParameters\fP
.RS 4
\fIversion\fP Version Number 
.br
\fImonth\fP Month 
.br
\fIyear\fP year 
.br
\fIauthor\fP Author 
.RE
.PP

.SS "void mml::help::header (std::string command, std::string option = \fC''\fP)\fC [noexcept]\fP"

.PP
Print out a header\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Command of the program 
.br
\fIoption\fP Necessary options 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
