.TH "mml::functions" 3 "Sat Jun 8 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::functions
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBmml::shell::arg\fP \fBvector\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBmml::shell::arg\fP \fBmml::functions::vector\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
