.TH "mml::time::time" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::time::time
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <time\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBhour\fP"
.br
.ti -1c
.RI "uint64_t \fBminute\fP"
.br
.ti -1c
.RI "uint64_t \fBsecond\fP"
.br
.ti -1c
.RI "uint64_t \fBmilliseconds\fP"
.br
.ti -1c
.RI "uint64_t \fBmicroseconds\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint64_t mml::time::time::hour"

.SS "uint64_t mml::time::time::microseconds"

.SS "uint64_t mml::time::time::milliseconds"

.SS "uint64_t mml::time::time::minute"

.SS "uint64_t mml::time::time::second"


.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
