.TH "mml::thread::Thread" 3 "Tue Jun 4 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::thread::Thread
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <thread\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThread\fP ()"
.br
.ti -1c
.RI "\fBThread\fP (const \fBThread\fP &thread_copy)"
.br
.ti -1c
.RI "\fBThread\fP (int max_i2)"
.br
.ti -1c
.RI "\fBThread\fP & \fBoperator=\fP (const \fBThread\fP &thread_temp)"
.br
.ti -1c
.RI "void \fBset_max_i\fP (int max_temp)"
.br
.ti -1c
.RI "void \fBthread_writing_true\fP ()"
.br
.RI "Set this thread to active writing\&. "
.ti -1c
.RI "void \fBthread_writing_false\fP ()"
.br
.RI "Set this thread to not actively writing\&. "
.ti -1c
.RI "bool \fBis_writing_active\fP ()"
.br
.RI "Checks if the thread is writing\&. "
.ti -1c
.RI "void \fBthread_sleep\fP (float second)"
.br
.RI "Sleep for a while\&. "
.ti -1c
.RI "void \fBthread_sleep_millisecond\fP (uint32_t millisecond)"
.br
.RI "Sleep for a while\&. "
.ti -1c
.RI "bool \fBwaiting\fP (int a=0)"
.br
.RI "Waits if many threads are writing if a not used, not always the same order of writing\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mml::thread::Thread::Thread ()\fC [inline]\fP"

.SS "mml::thread::Thread::Thread (const \fBThread\fP & thread_copy)\fC [inline]\fP"

.SS "mml::thread::Thread::Thread (int max_i2)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool mml::thread::Thread::is_writing_active ()"

.PP
Checks if the thread is writing\&. 
.PP
\fBReturns\fP
.RS 4
true = is writing 
.RE
.PP

.SS "\fBThread\fP& mml::thread::Thread::operator= (const \fBThread\fP & thread_temp)\fC [inline]\fP"

.SS "void mml::thread::Thread::set_max_i (int max_temp)\fC [inline]\fP"

.PP
\fBNote\fP
.RS 4
Die maximale Anzahl an vorhandenen Threads
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "void mml::thread::Thread::thread_sleep (float second)"

.PP
Sleep for a while\&. 
.PP
\fBParameters\fP
.RS 4
\fIsecond\fP Sleep for so many seconds 
.RE
.PP

.SS "void mml::thread::Thread::thread_sleep_millisecond (uint32_t millisecond)"

.PP
Sleep for a while\&. 
.PP
\fBParameters\fP
.RS 4
\fImillisecond\fP Sleep for so many miliseconds 
.RE
.PP

.SS "void mml::thread::Thread::thread_writing_false ()"

.PP
Set this thread to not actively writing\&. 
.SS "void mml::thread::Thread::thread_writing_true ()"

.PP
Set this thread to active writing\&. 
.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Programm: Thread\&.cpp
.PP
Enthält verschiedene Funktionen für Threads 
.SS "bool mml::thread::Thread::waiting (int a = \fC0\fP)"

.PP
Waits if many threads are writing if a not used, not always the same order of writing\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP wait for so many miliseconds\&. if a = 0 => random number is created in milliseconds 
.RE
.PP
\fBReturns\fP
.RS 4
true, when no thread is writing 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
