.TH "mml::thread" 3 "Thu May 23 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::thread
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThread\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsleep\fP (float s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mml::thread::sleep (float s)"

.PP
\fBNote\fP
.RS 4
Aktueller \fBThread\fP eine bestimmte Zeit lang stoppen
.RE
.PP
.PD 0
.IP "\(bu" 2
Second 
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
