.TH "mml::Unix" 3 "Mon Jun 10 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::Unix
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.PP
.RI "\fBfunctions\&.cpp\fP"
.br

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Funktionen 
.PP
.in +1c
.in +1c
.ti -1c
.RI "bool \fBexist\fP (std::string path)"
.br
.in -1c
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool mml::Unix::exist (std::string path)"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
