.TH "mml::functions" 3 "Sat May 25 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::functions
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBmml::shell::arg\fP \fBvector\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr uint32_t \fBconst_string_hash\fP (const char *\fBstring\fP)"
.br
.in -1c
.PP
.RI "\fBfunctions\&.cpp\fP"
.br

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Funktionen 
.PP
.in +1c
.in +1c
.ti -1c
.RI "uint32_t \fBcount_sym\fP (std::string test, char symbol)"
.br
.ti -1c
.RI "void \fBcout\fP (std::vector< std::string > vec)"
.br
.ti -1c
.RI "void \fBcout\fP (std::vector< \fBmml::string\fP > vec)"
.br
.ti -1c
.RI "void \fBcout\fP (std::vector< double > vec)"
.br
.ti -1c
.RI "void \fBcout\fP (std::vector< int > vec)"
.br
.ti -1c
.RI "std::string \fBdeclare_month\fP (int month_nr)"
.br
.ti -1c
.RI "std::vector< std::string > \fBerase\fP (std::vector< std::string > data)"
.br
.ti -1c
.RI "std::vector< \fBmml::string\fP > \fBerase\fP (std::vector< \fBmml::string\fP > data)"
.br
.ti -1c
.RI "std::vector< double > \fBerase\fP (std::vector< double > data)"
.br
.ti -1c
.RI "std::vector< int > \fBerase\fP (std::vector< int > data)"
.br
.ti -1c
.RI "int \fBget_random\fP (int min=0, int max=100)"
.br
.ti -1c
.RI "std::size_t \fBsmallest_num\fP (std::vector< std::size_t > values, std::size_t pos=0)"
.br
.ti -1c
.RI "std::string \fBrandom_str\fP (uint32_t letters=10, std::string value='')"
.br
.ti -1c
.RI "std::vector< double > \fBAdd_Vector\fP (std::vector< double > vector1, std::vector< double > vector2)"
.br
.ti -1c
.RI "std::vector< std::string > \fBAdd_Vector\fP (std::vector< std::string > vector1, std::vector< std::string > vector2)"
.br
.ti -1c
.RI "uint32_t \fBcifs\fP (std::string src, std::string dst, \fBmml::string\fP fstype, std::string user, std::string pass)"
.br
.ti -1c
.RI "std::size_t \fBdigits\fP (double number)"
.br
.ti -1c
.RI "std::vector< double > \fBGet_Values\fP (std::string filepath, int16_t min_value=0)"
.br
.ti -1c
.RI "void \fBgetline\fP (std::ifstream &input, \fBmml::string\fP &String)"
.br
.ti -1c
.RI "std::string \fBlower\fP (std::string input)"
.br
.ti -1c
.RI "double \fBMean_of_Vector\fP (std::vector< double > values, bool ausgabe=false)"
.br
.ti -1c
.RI "double \fBMean_of_Array\fP (double array[], uint16_t length, bool ausgabe=false)"
.br
.ti -1c
.RI "std::string \fBmount_Dir\fP (\fBmml::shell::arg\fP args, std::string mountpath, \fBstring\fP mountpoint, \fBstring\fP controlpoint, std::string user, std::string pass1, const char *fstype, int count)"
.br
.ti -1c
.RI "bool \fBunmount_dir\fP (std::string mount_dir, std::string controlpoint='')"
.br
.in -1c
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBmml::shell::arg\fP \fBmml::functions::vector\fP"

.SH "Function Documentation"
.PP 
.SS "std::vector< double > mml::functions::Add_Vector (std::vector< double > vector1, std::vector< double > vector2)"

.PP
\fBNote\fP
.RS 4
temporärer Dateiname erstellen
.RE
.PP
\fBReturns\fP
.RS 4
/tmp/c++_XXXXXX 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP
\fBNote\fP
.RS 4
Zwei Vektoren zu einem Vektor hinzufügen
.RE
.PP
\fBReturns\fP
.RS 4
double Vektor 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::vector< std::string > mml::functions::Add_Vector (std::vector< std::string > vector1, std::vector< std::string > vector2)"

.SS "uint32_t mml::functions::cifs (std::string src, std::string dst, \fBmml::string\fP fstype, std::string user, std::string pass)"

.PP
\fBNote\fP
.RS 4
Einhängen eines Netzwerklaufwerkes
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "constexpr uint32_t mml::functions::const_string_hash (const char * string)\fC [constexpr]\fP"

.PP
\fBNote\fP
.RS 4
Bilden eines Hashwertes zu einem String
.RE
.PP
\fBReturns\fP
.RS 4
Hashwert als Integerwert 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "uint32_t mml::functions::count_sym (std::string test, char symbol)"

.PP
\fBNote\fP
.RS 4
Anzahl eines Zeichens bestimmen
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "void mml::functions::cout (std::vector< double > vec)"

.SS "void mml::functions::cout (std::vector< int > vec)"

.SS "void mml::functions::cout (std::vector< \fBmml::string\fP > vec)"

.SS "void mml::functions::cout (std::vector< std::string > vec)"

.PP
\fBNote\fP
.RS 4
Inhalt eines Vektors ausgeben
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::string mml::functions::declare_month (int month_nr)"
Den Monatsname zum Monat bestimmen
.PP
\fBReturns\fP
.RS 4
Monatsname 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::size_t mml::functions::digits (double number)"

.PP
\fBNote\fP
.RS 4
Anzahl der Stellen eines doubles bestimmen
.RE
.PP
\fBReturns\fP
.RS 4
std::size_t 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::vector< double > mml::functions::erase (std::vector< double > data)"

.SS "std::vector< int > mml::functions::erase (std::vector< int > data)"

.SS "std::vector< \fBmml::string\fP > mml::functions::erase (std::vector< \fBmml::string\fP > data)"

.SS "std::vector< std::string > mml::functions::erase (std::vector< std::string > data)"

.PP
\fBNote\fP
.RS 4
Einen Vektor leeren
.RE
.PP
\fBReturns\fP
.RS 4
leeren Vektor 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "int mml::functions::get_random (int min = \fC0\fP, int max = \fC100\fP)"

.PP
\fBNote\fP
.RS 4
Eine Zufallszahl in bestimmten Grenzen erzeugen
.RE
.PP
\fBReturns\fP
.RS 4
Zufallszahl 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::vector< double > mml::functions::Get_Values (std::string filepath, int16_t min_value = \fC0\fP)"

.PP
\fBNote\fP
.RS 4
Umwandeln von und zu einem String oder Char
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP
\fBNote\fP
.RS 4
Zahlenwerte aus einer Datei in einen Vektor schreiben
.RE
.PP
\fBReturns\fP
.RS 4
double Vektor 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "void mml::functions::getline (std::ifstream & input, \fBmml::string\fP & String)"

.PP
\fBNote\fP
.RS 4
aus einer Datei eine Zeile auslesen
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::string mml::functions::lower (std::string input)"

.PP
\fBNote\fP
.RS 4
Alle Werte im String als Kleinbuchstaben
.RE
.PP
\fBReturns\fP
.RS 4
String mit Kleinbuchstaben 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "double mml::functions::Mean_of_Array (double array[], uint16_t length, bool ausgabe = \fCfalse\fP)"

.SS "double mml::functions::Mean_of_Vector (std::vector< double > values, bool ausgabe = \fCfalse\fP)"

.PP
\fBNote\fP
.RS 4
Durchschnitt berechnen aus den Werten in einem Vektor oder Array
.RE
.PP
\fBReturns\fP
.RS 4
Durchschnittswert 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::string mml::functions::mount_Dir (\fBmml::shell::arg\fP args, std::string mountpath, \fBmml::string\fP mountpoint, \fBmml::string\fP controlpoint, std::string user, std::string pass1, const char * fstype, int count)"

.PP
\fBNote\fP
.RS 4
Bestimmung von Dateien zur Einbindung eines Laufwerkes in der Funktion cifs
.RE
.PP
\fBReturns\fP
.RS 4
Passwort 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::string mml::functions::random_str (uint32_t letters = \fC10\fP, std::string value = \fC''\fP)"

.PP
\fBNote\fP
.RS 4
Anpingen einer IP-Adresse oder eines Strings mit pip install pyping installieren, wenn nicht vorhanden -lpython2\&.7 notwendig
.RE
.PP
\fBReturns\fP
.RS 4
true, wenn erreichbar 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP
\fBNote\fP
.RS 4
Eine Zufallsstring in Kleinbuchstaben erzeugen
.RE
.PP
\fBReturns\fP
.RS 4
Zufallsstring 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "std::size_t mml::functions::smallest_num (std::vector< std::size_t > values, std::size_t pos = \fC0\fP)"

.PP
\fBNote\fP
.RS 4
Eine Linie aus einer geöffneten Datei zurückgeben
.RE
.PP
\fBReturns\fP
.RS 4
Zeile aus einer Datei 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP
\fBNote\fP
.RS 4
Kleinste Zahl herausfinden
.RE
.PP
\fBReturns\fP
.RS 4
kleinste Zahl 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "bool mml::functions::unmount_dir (std::string mount_dir, std::string controlpoint = \fC''\fP)"

.PP
\fBNote\fP
.RS 4
Aushängen eines Laufwerkes
.RE
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Arguments passed to the function 
.br
\fImountpath\fP String, where the directory is mounted
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
