.TH "mml::help" 3 "Tue May 21 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mml::help
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcheck_root\fP ()"
.br
.ti -1c
.RI "void \fBcifs\fP ()"
.br
.ti -1c
.RI "void \fBconvert\fP ()"
.br
.ti -1c
.RI "void \fBcop\fP ()"
.br
.ti -1c
.RI "void \fBcopy\fP ()"
.br
.ti -1c
.RI "void \fBfarben\fP ()"
.br
.ti -1c
.RI "void \fBfinanzen\fP ()"
.br
.ti -1c
.RI "void \fBhhelp\fP ()"
.br
.ti -1c
.RI "void \fBhhelp_commands\fP ()"
.br
.ti -1c
.RI "void \fBR_cop\fP ()"
.br
.ti -1c
.RI "void \fBR_dns_filter\fP ()"
.br
.ti -1c
.RI "void \fBrechner\fP ()"
.br
.ti -1c
.RI "void \fBsizeof_h\fP ()"
.br
.ti -1c
.RI "void \fBstatistik\fP ()"
.br
.ti -1c
.RI "void \fBtimer\fP ()"
.br
.ti -1c
.RI "void \fBtodos\fP ()"
.br
.ti -1c
.RI "void \fBuserinfo\fP ()"
.br
.ti -1c
.RI "void \fBfoot\fP (std::string version, std::string month, int year)"
.br
.ti -1c
.RI "void \fBheader\fP (std::string befehl, std::string option='')"
.br
.ti -1c
.RI "void \fBhelp\fP (\fBmml::string\fP output)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mml::help::check_root ()"

.PP
\fBNote\fP
.RS 4
Ausgabe der jeweiligen Hilfetexte
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "void mml::help::cifs ()"

.SS "void mml::help::convert ()"

.SS "void mml::help::cop ()"

.SS "void mml::help::copy ()"

.SS "void mml::help::farben ()"

.SS "void mml::help::finanzen ()"

.SS "void mml::help::foot (std::string version, std::string month, int year)"

.PP
\fBNote\fP
.RS 4
Ausgabe der Fußzeile mit Angabe zum Autor und Datum 
.RE
.PP
\fBParameters\fP
.RS 4
\fIstring\fP Version Number 
.br
\fIstring\fP Month 
.br
\fIint\fP year 
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "void mml::help::header (std::string befehl, std::string option = \fC''\fP)"

.PP
\fBNote\fP
.RS 4
Ausgabe des Headers, dass nur von Variablen abhängig ist
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "void mml::help::help (\fBmml::string\fP output)"

.PP
\fBNote\fP
.RS 4
Ausgabe in der Konsole
.RE
.PP
\fBAuthor\fP
.RS 4
Mike 
.RE
.PP

.SS "void mml::help::hhelp ()"

.SS "void mml::help::hhelp_commands ()"

.SS "void mml::help::R_cop ()"

.SS "void mml::help::R_dns_filter ()"

.SS "void mml::help::rechner ()"

.SS "void mml::help::sizeof_h ()"

.SS "void mml::help::statistik ()"

.SS "void mml::help::timer ()"

.SS "void mml::help::todos ()"

.SS "void mml::help::userinfo ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
