.TH "src/shell.cpp" 3 "Sat May 25 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shell.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'mml/definitions\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br
\fC#include 'mml\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmml::string\fP \fBmml_pass\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmml::string\fP mml_pass\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
