.TH "src/standards.cpp" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/standards.cpp \- Contains different standard functions of this library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include 'mml/definitions\&.hpp'\fP
.br
\fC#include 'mml/Unix\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Contains different standard functions of this library\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-13
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
