.TH "src/standards.cpp" 3 "Tue May 21 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/standards.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <definitions\&.hpp>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <sys/mount\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <mml\&.hpp>\fP
.br
\fC#include 'standards\&.hpp'\fP
.br

.SS "Functions"

.PP
.RI "\fBstandards\&.cpp\fP"
.br

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Standardfunktionen 
.PP
.in +1c
.in +1c
.ti -1c
.RI "template void \fBmml::cout< mml::string >\fP (std::vector< \fBmml::string\fP > const &vec)"
.br
.ti -1c
.RI "template void \fBmml::cout< std::string >\fP (std::vector< std::string > const &vec)"
.br
.in -1c
.in -1c
.SH "Function Documentation"
.PP 
.SS "template void \fBmml::cout\fP< \fBmml::string\fP > (std::vector< \fBmml::string\fP > const & vec)"

.SS "template void \fBmml::cout\fP< std::string > (std::vector< std::string > const & vec)"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
