.TH "include/mml/standards.hpp" 3 "Mon Jun 10 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/standards.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <random>\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'mml/definitions\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmml::string\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmml\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename templ > double \fBmml::atob\fP (const templ &t) noexcept"
.br
.RI "Converts value to bool\&. "
.ti -1c
.RI "template<typename T > double \fBmml::atof\fP (const T &t) noexcept"
.br
.RI "Converts value to bool\&. "
.ti -1c
.RI "template<typename T > int \fBmml::atoi\fP (const T &t) noexcept"
.br
.RI "Converts value to int\&. "
.ti -1c
.RI "template<typename templ > void \fBmml::cout\fP (std::vector< templ > const &vec) noexcept"
.br
.ti -1c
.RI "template<typename T > \fBmml::string\fP \fBmml::to_string\fP (const T &t) noexcept"
.br
.RI "Convert value to \fBmml::string\fP\&. "
.ti -1c
.RI "constexpr uint32_t \fBmml::const_string_hash\fP (const char *string) noexcept"
.br
.RI "Forms a hash value of a string\&. "
.ti -1c
.RI "template<typename templ > void \fBmml::erase\fP (std::vector< templ > &data) noexcept"
.br
.RI "Empty a vector\&. "
.in -1c
.PP
.RI "\fBstandards\&.cpp\fP"
.br
Contains different standard functions of this library
.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP

.PP
.in +1c
.in +1c
.ti -1c
.RI "bool \fBmml::check_root\fP (std::string programme='')"
.br
.RI "Check if program executed as root\&. "
.ti -1c
.RI "uint32_t \fBmml::date\fP (int info, time_t time1=\-1) noexcept"
.br
.RI "Returns the wished info from the time (like date etc\&.) Options are: "
.ti -1c
.RI "std::string \fBmml::date\fP (time_t time1=\-1, \fBmml::string\fP value='Date+Time', std::string separator1=':', std::string separator2='\&.') noexcept"
.br
.RI "Returns the date and/or time as a std::string\&. "
.ti -1c
.RI "bool \fBmml::is_num\fP (char c) noexcept"
.br
.RI "Checks if a character is a number\&. "
.ti -1c
.RI "bool \fBmml::range\fP (std::size_t number) noexcept"
.br
.RI "Checks if a number has reached the maximum value (std::string::npos) "
.ti -1c
.RI "bool \fBmml::range\fP (std::size_t number1, std::size_t number2) noexcept"
.br
.RI "Checks if one of two numbers has reached the maximum value\&. "
.ti -1c
.RI "double \fBmml::round\fP (double number, uint16_t digits) noexcept"
.br
.RI "round a number "
.ti -1c
.RI "std::string \fBmml::declare_month\fP (int month_nr) noexcept"
.br
.RI "Convert month number to month string\&. "
.ti -1c
.RI "template<typename templ > templ \fBmml::get_random\fP (templ min=0, templ max=100) noexcept"
.br
.RI "Create a random number in a defined range\&. "
.ti -1c
.RI "template<typename templ > templ \fBmml::smallest_num\fP (std::vector< templ > values, std::size_t pos=0)"
.br
.RI "Return the smallest number\&. "
.ti -1c
.RI "std::string \fBmml::random_str\fP (size_t letters=10, std::string start='') noexcept"
.br
.RI "Create a random, lower-case string\&. "
.ti -1c
.RI "std::size_t \fBmml::digits\fP (double number) noexcept"
.br
.RI "Determine number of digits of a double number\&. "
.in -1c
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Contains several standard functions and the class string 
.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
