.TH "src/standards.cpp" 3 "Wed May 22 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/standards.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <sys/mount\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include 'mml/functions\&.hpp'\fP
.br
\fC#include 'mml/definitions\&.hpp'\fP
.br
\fC#include 'mml/Unix\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
