.TH "src/string.cpp" 3 "Tue Jun 4 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/string.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br
\fC#include 'mml/file\&.hpp'\fP
.br
\fC#include 'mml/Unix\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mike Moser
.RE
.PP
Enthält verschiedene Funktionen 
.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
