.TH "src/string.cpp" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/string.cpp \- Function definitions of the class string\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include 'mml/string\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br
\fC#include 'mml/file\&.hpp'\fP
.br
\fC#include 'mml/Unix\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Function definitions of the class string\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-13
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
