.TH "test/test1.cpp" 3 "Wed May 22 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test1.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include 'mml\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
