.TH "test/test_file.cpp" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_file.cpp \- Tests for \fBfile\&.hpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'mml/file\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBassert_msg\fP(cond,  msg)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests for \fBfile\&.hpp\fP\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-13
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define assert_msg(cond, msg)"
\fBValue:\fP
.PP
.nf
    do { \
        if (!(cond)) { \
            std::cerr << "Assertion failed: (" #cond "), function " << __func__ \
                      << ", file " << __FILE__ << ", line " << __LINE__ << "\&." << std::endl \
                      << "Message: " << msg << std::endl; \
            std::abort(); \
        } \
    } while (false)
.fi
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
