.TH "include/mml/thread.hpp" 3 "Mon Jun 10 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mml/thread.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <future>\fP
.br
\fC#include <mutex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmml::thread::Threads< result >\fP"
.br
.RI "Class \fBThreads\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmml\fP"
.br
.ti -1c
.RI " \fBmml::thread\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmml::thread::sleep\fP (float s) noexcept"
.br
.RI "Stop actual thread for a specific time\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
