.TH "src/time.cpp" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/time.cpp \- Source File to \fBtime\&.hpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'mml/time\&.hpp'\fP
.br
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include 'mml/string\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Source File to \fBtime\&.hpp\fP\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-13
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
