.TH "src/time.cpp" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/time.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'mml/time\&.hpp'\fP
.br
\fC#include 'mml/standards\&.hpp'\fP
.br
\fC#include 'mml/shell\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
