.TH "src/Timer.cpp" 3 "Mon Jun 10 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Timer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'mml/Timer\&.hpp'\fP
.br
\fC#include 'mml/standards\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmml::Timer::time\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fBmml::Timer\fP &t, std::ostream &os)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (\fBmml::Timer\fP & t, std::ostream & os)"

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
