.TH "todo" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBmml::file::copy\fP (\fBmml::string\fP src, \fBmml::string\fP dst, std::string name_in='', std::string name_ex='', size_t blocksize=_100MB, bool verbose=false, bool verbose_debug=false, bool all=false, bool recursive=false, bool force=false, bool progress=false, bool falsewrite=false)\fP" 1c
Copy symbolic and hard link file by creating them 
.PP

