.TH "src/Unix.cpp" 3 "Thu May 23 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Unix.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <pwd\&.h>\fP
.br
\fC#include <grp\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <bits/local_lim\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <utime\&.h>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include 'mml\&.hpp'\fP
.br
\fC#include 'mml/file\&.hpp'\fP
.br
\fC#include 'mml/Unix\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
