.TH "src/User.cpp" 3 "Tue Aug 13 2024" "mml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/User.cpp \- Function definitions for the class User\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <net/if\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <locale>\fP
.br
\fC#include 'mml/Unix\&.hpp'\fP
.br
\fC#include 'mml/file\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Function definitions for the class User\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Moser 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-13
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mml from the source code\&.
