build-job:
  stage: build
  script:
    - mkdir build
    - cmake ..
    - make -j5
  artifacts:
    paths:
      - "build/"

test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - cd build
    - make test
